#!/usr/bin/php
<?php
$addr = (isset($_ENV["MUNIN_FLUXY_ADDR"])) ? $_ENV["MUNIN_FLUXY_ADDR"] : "127.0.0.1";
$port = (isset($_ENV["MUNIN_FLUXY_PORT"])) ? $_ENV["MUNIN_FLUXY_PORT"] : "8888";

$link = topy_pconnect($addr, $port);
if (!$link) {
	die("Could not connect to server Fluxy at $addr:$port\n");
}

$stats = topy_query($link, "stats");
if (!isset($stats["commands"]))
	die();

$commands = $stats["commands"];
arsort($commands);

if ($argc == 2 and $argv[1] == "config") {
	echo "graph_title Fluxy queries\n";
	echo "graph_vlabel queries per second\n";
	echo "graph_category Fluxy\n";
	echo "graph_info This graph shows the rate of Fluxy queries (on $addr:$port)\n";

	foreach ($commands as $key => $value) {
		$field = str_replace("::", "_", $key);
		echo "command_".$field.".type DERIVE\n"; 
		echo "command_".$field.".label ".$key."\n";
		echo "command_".$field.".max 10000\n";
		echo "command_".$field.".min 0\n";
	}
	die();
}

foreach ($commands as $key => $value) {
	$field = str_replace("::", "_", $key);
	echo "command_".$field.".value ".$value."\n";
}

?>
