#!/usr/bin/php
<?php
$addr = (isset($_ENV["MUNIN_FLUXY_ADDR"])) ? $_ENV["MUNIN_FLUXY_ADDR"] : "127.0.0.1";
$port = (isset($_ENV["MUNIN_FLUXY_PORT"])) ? $_ENV["MUNIN_FLUXY_PORT"] : "8888";

$link = topy_pconnect($addr, $port);
if (!$link) {
	die("Could not connect to server Fluxy at $addr:$port\n");
}

$stats = topy_query($link, "addstats");
if (!is_array($stats))
	die();

arsort($stats);

if ($argc == 2 and $argv[1] == "config") {
	echo "graph_title Fluxy addstats\n";
	echo "graph_vlabel added messages by type\n";
	echo "graph_category Fluxy\n";
	echo "graph_info This graph shows the rate of add messages by type (on $addr:$port)\n";

	foreach ($stats as $key => $value) {
		echo "item_".$key.".type DERIVE\n"; 
		echo "item_".$key.".label ".$key."\n";
		echo "item_".$key.".max 10000\n";
		echo "item_".$key.".min 0\n";
	}
	die();
}

foreach ($stats as $key => $value) {
	echo "item_".$key.".value ".$value."\n";
}

?>
