/*
 *  Copyright (C) 2009 Nicolas Vion <nico@picapo.net>
 *
 *   This file is part of Fluxy.
 *
 *   Fluxy is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   Fluxy is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with Fluxy; if not, write to the Free Software
 *   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

//This script was generated by php/mk_macros.php
//Don't change manually!

#ifndef _HELP_HH
#define _HELP_HH

#define HELP_SERVER \
	"list of commands:\n" \
	"=================\n" \
	"TID <n> <command>\n" \
	"	Give a Transaction Id that will be returned with the command's result\n" \
	"info\n" \
	"	Get server information\n" \
	"quit\n" \
	"	Close connection with client\n" \
	"stats\n" \
	"	Get statistics about server\n" \
	"addstats\n" \
	"	Get statistics about type of added messages\n" \
	"recycler stats\n" \
	"	Get statistics about memory recycler\n" \
	"autodump <command>\n" \
	"	Execute a command on autodump\n" \
	"	See \"autodump help\" for more information\n" \
	"help\n" \
	"	Show commands list\n" \
	"mode <text|php_serialize|none>\n" \
	"	Set default output format\n" \
	"user <user_id> <command> [args]\n" \
	"	Execute a command on a existing user\n" \
	"	See \"user <user_id> help\" for more information\n" \
	"user* <user_id> <command> [args]\n" \
	"	Execute a command on a user.\n" \
	"	Create a new user if <user_id> doesn't exists\n" \
	"send <user_id1>,<user_id2>,... <id> <date> <type> <flags> <version> <body>\n" \
	"	Send a message to a set of users\n" \
	"fetch <user_id1> [ [<mask> <value>] ], <user_id2>,... [before <date>] [limit <n = 128>]\n" \
	"	Fetch messages from a set of users\n" \
	"dump <path>\n" \
	"	Dump data in file <path>\n" \
	"parse\n" \
	"	Parse queries file\n" \
	"report\n" \
	"	Generate report\n" \
	"top [limit <n = 128>]\n" \
	"	Generate top\n" \
	"cleanup\n" \
	"	Delete old messages to free memory\n" 

#define HELP_USER \
	"list of commands:\n" \
	"=================\n" \
	"messages add <id>|auto <date>|now <type> <flags> <version> <body>\n" \
	"	Add new message\n" \
	"messages delete <id>[:<type>]\n" \
	"	Delete message\n" \
	"messages update <id>[:<type>] [date <date>] [type <type>] [flags <flags>] [version <version>] [seen <1/0>] [body <body>]\n" \
	"	Update message\n" \
	"messages get\n" \
	"	Get messages\n" \
	"messages seen all|last <id>[:<type>]\n" \
	"	Mark messages as seen\n" \
	"messages count [unseen]\n" \
	"	Count messages\n" \
	"messages clear\n" \
	"	Clear messages\n" \
	"data set\n" \
	"	Get data\n" \
	"data get\n" \
	"	Get data\n" \
	"data clear\n" \
	"	Clear data\n" \
	"get\n" \
	"	Get user\n" \
	"show\n" \
	"	Show user data\n" \
	"delete\n" \
	"	Delete user\n" \
	"clear\n" \
	"	Clear user\n" \
	"help\n" \
	"	Show commands list\n" 

#define HELP_AUTODUMP \
	"list of commands:\n" \
	"=================\n" \
	"stats\n" \
	"	Get stats about last autodump\n" \
	"get\n" \
	"	Get autodump settings\n" \
	"set <target> <delay>\n" \
	"	Set autodump settings\n" \
	"disable\n" \
	"	Disable autodump\n" \
	"force\n" \
	"	Force autodump\n" \
	"help\n" \
	"	Show commands list\n" 


#endif
