/*
 *  Copyright (C) 2009 Nicolas Vion <nico@picapo.net>
 *
 *   This file is part of Fluxy.
 *
 *   Fluxy is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   Fluxy is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with Fluxy; if not, write to the Free Software
 *   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

//This script was generated by php/mk_macros.php
//Don't change manually!

#ifndef _HELP_HH
#define _HELP_HH

<?
function mk_define($name, $lines) {
	echo "#define $name \\\n";
	$sep = "";
	foreach($lines as $line) {
		echo $sep."\t".'"'.str_replace('"', '\\"', $line).'" ';
		$sep = "\\\n";
	}
	echo "\n\n";
}

function extract_help($f) {
	$tbl = array(
		"list of commands:\\n",
		"=================\\n"
	);
	foreach ($f as $line) {
		$line = ltrim($line);
		if (ereg("//!(.*)", $line, $args))
			$tbl[] =  rtrim($args[1]).'\\n';
	}
	//array_push($tbl, substr(array_pop($tbl), 0, -2));
	return $tbl;
}

mk_define("HELP_SERVER", extract_help(array_merge(file(dirname(__FILE__)."/server.cc"), file(dirname(__FILE__)."/users.cc"))));
mk_define("HELP_USER", extract_help(file(dirname(__FILE__)."/user.cc")));
mk_define("HELP_AUTODUMP", extract_help(file(dirname(__FILE__)."/autodump.cc")));
?>

#endif
